version: '3.6'
volumes:
  api_data: {}
  phame_data: {}
  postgres_data_local: {}
  postgres_backup_local: {}

services:

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - phame

 # flask app that calls shell script that runs phame
  phame-app:
    build:
      context: ./services/phame-app
      dockerfile: Dockerfile
      args:
        http_proxy: http://proxyout.lanl.gov:8080
        https_proxy: http://proxyout.lanl.gov:8080
    depends_on:
      - redis
    expose:
      - 5001
    volumes:
      - phame_data:/phame_api/media
      - api_data:/usr/src/app/static/uploads

  # flask-based API
  phame:
    build:
      context: ./services/phame
      dockerfile: Dockerfile-dev
      args:
        http_proxy: http://proxyout.lanl.gov:8080
        https_proxy: http://proxyout.lanl.gov:8080
    volumes:
      - './services/phame:/usr/src/app'
      - phame_data:/phame_api/media
      - api_data:/usr/src/app/static/uploads
    expose:
      - 5000
    env_file:
      - ./.envs/.local/.phame
    environment:
      - FLASK_ENV=development
      - FLASK_APP=project/__init__.py
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@phame-db:5432/phame_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@phame-db:5432/phame_test
      - SECRET_KEY=my_precious
    depends_on:
      - phame-db

  phame-db:
    build:
      context: ./services/phame/project/db
      dockerfile: Dockerfile
      args:
        http_proxy: http://proxyout.lanl.gov:8080
        https_proxy: http://proxyout.lanl.gov:8080
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    ports:
    - 5435:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  monitor:
    build:
      context: ./services/celery-queue
      dockerfile: Dockerfile
      args:
        http_proxy: http://proxyout.lanl.gov:8080
        https_proxy: http://proxyout.lanl.gov:8080
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis
