version: '3.2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}
  django_data: {}
  phame_data: {}


services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: phame_api01_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres

  nginx:
    image: nginx
    volumes:
     - ./compose/local/nginx/conf.d:/etc/nginx/conf.d
    ports:
     - "8080:80"
    depends_on:
      - web

  phame:
    build:
      context: .
      dockerfile: ./compose/local/PhaME-1/Dockerfile
    env_file:
      - ./.envs/.local/.postgres
    depends_on:
#      - postgres
      - redis
    ports:
      - 5000:5000
    volumes:
      - .:/phame_api01
      - phame_data:/app/static/trees

  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.envs/.local/.postgres
    ports:
     - 5000:5000
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/phame_api01

  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
