version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: phame_api01_production_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: phame_api01_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    image: nginx
    volumes:
     - ./compose/local/nginx/conf.d:/etc/nginx/conf.d
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=edge-bioinformatics-test.org
     - NGINX_PORT=80


  redis:
    image: redis:3.2

  phame:
    build:
      context: .
      dockerfile: ./compose/local/PhaME-1/Dockerfile
    image: phame_api01_phame-1
    hostname: phame_host
    ports:
      - 5000:5000
    volumes:
      - .:/phame_api01
