sudo: required
language: perl
perl:
  - "5.16"

before_install:
  # - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

install:
  - ./INSTALL.sh

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
  - PWD=$(pwd)
  - sh test/TestAll.sh
  - cover -test

after_success:
  - cover -report codecov