# Generated by Django 2.0.6 on 2018-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='ref_file',
            field=models.FileField(default='None', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='project',
            field=models.CharField(default='ecoli', max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='reference',
            field=models.CharField(choices=[('0', 'random'), ('1', 'given'), ('2', 'ANI')], max_length=6),
        ),
    ]
