# Generated by Django 2.0.6 on 2018-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0002_auto_20180625_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='bootstrap',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=3),
        ),
        migrations.AlterField(
            model_name='run',
            name='cds_snps',
            field=models.CharField(default=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='run',
            name='clean',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=3),
        ),
        migrations.AlterField(
            model_name='run',
            name='code',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='data',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', 'realignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='first_time',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=3),
        ),
        migrations.AlterField(
            model_name='run',
            name='pos_select',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='reads',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='ref_dir',
            field=models.FileField(null=True, upload_to='refdir'),
        ),
        migrations.AlterField(
            model_name='run',
            name='ref_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='reference',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=6),
        ),
        migrations.AlterField(
            model_name='run',
            name='tree',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='work_dir',
            field=models.FileField(null=True, upload_to='workdir'),
        ),
    ]
