# Generated by Django 2.0.6 on 2018-06-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0003_auto_20180626_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='data',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=20),
        ),
    ]
