# Generated by Django 2.0.6 on 2018-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0005_auto_20180626_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='reference',
            field=models.CharField(choices=[('random', '0'), ('given', '1'), ('ANI', '2')], max_length=6),
        ),
    ]
