# Generated by Django 2.0.6 on 2018-06-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0006_auto_20180626_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='buildSNPdb',
            field=models.CharField(choices=[('0', 'only align to reference'), ('1', 'build SNP database')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='cds_snps',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='data',
            field=models.CharField(choices=[('0', 'F'), ('1', 'C'), ('2', 'R'), ('3', 'F+C'), ('4', 'F+R'), ('5', 'C+R'), ('6', 'F+C+R'), ('7', 'realignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='first_time',
            field=models.CharField(choices=[('1', 'yes'), ('2', 'update existing SNP alignment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='reads',
            field=models.CharField(choices=[('0', 'single reads'), ('1', 'paired reads'), ('3', 'both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='reference',
            field=models.CharField(choices=[('0', 'random'), ('1', 'given'), ('2', 'ANI')], max_length=6),
        ),
    ]
