# Generated by Django 2.0.6 on 2018-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0007_auto_20180627_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='buildSNPdb',
            field=models.CharField(choices=[('0', 'only align to reference'), ('1', 'build SNP database')], max_length=40),
        ),
        migrations.AlterField(
            model_name='run',
            name='code',
            field=models.CharField(choices=[('0', 'Bacteria'), ('1', 'Virus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='first_time',
            field=models.CharField(choices=[('1', 'yes'), ('2', 'update existing SNP alignment')], max_length=40),
        ),
        migrations.AlterField(
            model_name='run',
            name='pos_select',
            field=models.CharField(choices=[('0', 'no'), ('1', 'PAML'), ('2', 'HyPhy'), ('3', 'both')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='tree',
            field=models.CharField(choices=[('0', 'no tree'), ('1', 'FastTree'), ('2', 'RAxML'), ('3', 'both')], max_length=20),
        ),
    ]
