# Generated by Django 2.0.6 on 2018-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0008_auto_20180627_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='bootstrap',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], max_length=3),
        ),
        migrations.AlterField(
            model_name='run',
            name='clean',
            field=models.CharField(choices=[('0', 'no'), ('1', 'yes')], max_length=3),
        ),
    ]
