# Generated by Django 2.0.6 on 2018-06-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0009_auto_20180627_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='cds_snps',
            field=models.CharField(choices=[('0', 'no cds SNPs'), ('1', 'cds SNPs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='reads',
            field=models.CharField(choices=[('0', 'single reads'), ('1', 'paired reads'), ('2', 'both')], max_length=20),
        ),
    ]
