# Generated by Django 2.0.6 on 2018-06-27 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phame_app', '0011_run_aligner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_file', models.FileField(upload_to='refdir')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_file', models.FileField(upload_to='workdir')),
            ],
        ),
        migrations.AlterField(
            model_name='run',
            name='ref_dir',
            field=models.FilePathField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='work_dir',
            field=models.FilePathField(null=True),
        ),
        migrations.AddField(
            model_name='workfile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phame_app.Run'),
        ),
        migrations.AddField(
            model_name='referencefile',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phame_app.Run'),
        ),
    ]
