"""empty message

Revision ID: 1f45dc7e73d7
Revises: 2519cd4197f8
Create Date: 2019-08-30 21:54:14.517385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f45dc7e73d7'
down_revision = '2519cd4197f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET active = true")
    op.alter_column('users', 'active', nullable=False)
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET created_date = NOW()")
    op.alter_column('users', 'created_date', nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_date')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
