"""empty message

Revision ID: 3aa94636375a
Revises: 21ab1e364259
Create Date: 2019-06-03 22:34:59.140344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa94636375a'
down_revision = '21ab1e364259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###
