name: phame_api01
dependencies:
  - numpy
  - pandas=0.23.1
  - pip:
    - amqp==2.2.2
    - Babel==2.5.3
    - billiard==3.5.0.3
    - celery==4.2.0
    - click==6.7
    - Flask==1.0.2
    - flask-login
    - flask-migrate
    - flask-sqlalchemy
    - flask-wtf
    - itsdangerous==0.24
    - Jinja2==2.10
    - kombu==4.2.1
    - MarkupSafe==1.0
    - psycopg2
    - pytz==2018.3
    - redis==2.10.1
    - tornado==5.0.2
    - vine==1.1.4
    - Werkzeug==0.14.1
    - requests
